### ISSUE TITLE
Draft MPD architecture diagram

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#63]
Create a conceptual architecture diagram for data flows within ATD related to the Mobility Project Database

**Comment by zappfyllc** [comment]
Draft Mobility Project Database System Context (WIP): https://drive.google.com/open?id=1qFOa1QIKkD-xFJDn966pOqRGXWMD78Wq

**Comment by zappfyllc** [comment]
Diagram updated after sprint review and ATD language changed to avoid confusion...@johnclary when you are back, please take a look at this and let me know what you think. We would like to utilize this for discussions with the DTS team and helping make scope decisions.

**Comment by johnclary** [comment]
@zappfyllc this looks good, with a few changes. I’m happy to talk you and @amenity through this ahead of further discussion with the devs. Let me know.

1. Add "Vision Zero Database" as a work-group specific application. 

2. Add ArcGIS Online as an app in the city ecosystem. There is a good chance we will push and pull data from ArcGIS Online, so you can indicate as such on the diagram.

3. Add "Open Data Portal (Socrata)" as an app in the city ecosystem. Our preferred architecture for public-facing dashboards, e.g., the Mobility Project Explorer, is that the dashboard web app pulls live data (JSON over HTTPS) directly from the Open Data Portal using the data portal API. This is the model we use for the Vision Zero Viewer and [the traffic signal dashboards](http://data.mobility.austin.gov/). So your diagram can be updated with a push arrow from MPD to the Open Data Portal, and from the Open Data Portal to the Mobility Project Viewer.

4. I don’t know a whole lot  about the CIP feature class, but I expect that we will maintain at least one other Esri feature class with MPD data. This feature class would live on ArcGIS Online, which is a service that you can add to the city ecosystem. We will probably be pushing and pulling JSON over HTTPS to ArcGIS Online.

**Comment by zappfyllc** [comment]
@johnclary makes sense: let's definitely meet prior to the discussion with the team (@amenity could you facilitate scheduling this for the three of us, since I'm not sure when we're scheduling the full team meeting?) just to ensure we're on the same page, but I did go ahead and make the changes to the diagram. Some thoughts that emerged from the sprint review surrounding the diagram (don't need an answer immediately, we can discuss during our meeting):

1. Do we consider the Mobility Project Explorer/Viewer only the public-facing tool? For example, there have been use cases discussed in user interview sessions that have touched on a need for workgroups to see other projects in a geospatial view, however, the amount of detail needed in that view compared to what the public sees is a little unclear to me. Personally I would think that you could just house a link on the public-facing dashboard that sent users (e.g. the city employees) to further details of a project located in the Mobility Project Database. But if there's a strong need to have geospatial information displayed that wouldn't otherwise be displayed to the public, then I'm guessing ArcGIS Online would be the solution?

2. re: Vision Zero Database/Viewer: should I be treating these as two different things or should it just be "Vision Zero Database" underneath Workgroup-Specific Apps (I previously had the viewer under the City Ecosystem)? FWIW, I really like treating the database/application that actually performs CRUDL operations separate from a read-only application (e.g. essentially a dashboard), but I wasn't sure which you meant. I've removed Vision Zero Viewer from the city ecosystem for now and just placed Vision Zero Database in the workgroup-specific application bubble.

**Comment by amenity** [comment]
@zappfyllc - updated diagram [here](https://www.draw.io/#G11_XUucbN_ZzAVEhpNTyMehSMVvJ7Y_TO) based on today's meeting with the dev team and a later discussion with @johnclary.  
Feel free to modify or ask questions and close this issue when you're comfortable with this first pass.
